### PR TITLE
fix `tqdm`

### PR DESCRIPTION
**Pull request by aaronspring**

### CODE REVIEW

**Comment by observingClouds** [comment]
You were to quick with the merge :D Just made an update to the progress_bar branch...

**Comment by observingClouds** [comment]
I made the same changes...feel free to merge this

**Comment by aaronspring** [comment]
I wonder why this didnt come up in CI

**Comment by observingClouds** [comment]
The CI did actually fail: https://github.com/observingClouds/bitinformation_pipeline/runs/6004605391?check_suite_focus=true

**Comment by aaronspring** [comment]
probably the tqdm.auto does some magic where GHA CI is different to supercomputer.

**Comment by aaronspring** [comment]
ok. then I just ignored it...

**Pull request merged**
